
language: python
before_script:
  - sleep 3
python:
  - "3.6"
# command to install dependencies
install:
  - sudo apt-get install python-opengl
  - sudo apt update && sudo apt install -y python3-dev python3-pip libjpeg-dev zlib1g-dev python-gst-1.0
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt
# command to run tests
script:
- pylint *.py
- xvfb-run -s "-screen 0 1400x900x24" pytest test_space.py
